apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: "nginx"
  name: {{ .Values.application.name }}-ingress
spec:
  rules:
  - host: {{ .Values.application.vhost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.application.name }}-service
            port:
              number: {{ .Values.application.port }}
