apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-service
spec:
  ports:
  - name: {{ .Values.application.port | quote }}
    port: {{ .Values.application.port }}
    targetPort: {{ .Values.application.port }}
  selector:
    app: {{ .Values.application.name }}
  type: ClusterIP
